#Problem 2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
#the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.

a = 0
b = 1
fnum = 0
sum = 0

#While loop to run till fibonacci <= 4 million
while fnum <= 4000000:
    fnum = a + b
    print(fnum)
    a = b
    b = fnum
    if fnum % 2 == 0:
        sum += fnum

sum